package com.yaetoti.gif.blocks;

public enum GifElementType {
  HEADER,
  LOGICAL_SCREEN_DESCRIPTOR,
  COLOR_TABLE,
  IMAGE_DESCRIPTOR,
  TABLE_BASED_IMAGE_DATA,
  TRAILER,
  APPLICATION_EXTENSION,
  GRAPHIC_CONTROL_EXTENSION,
  COMMENT_EXTENSION,
  PLAIN_TEXT_EXTENSION,
}
